# Generated by Django 4.0 on 2022-05-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_articles_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_image',
            field=models.ImageField(default='static/images/user2.png', upload_to='articles/'),
        ),
    ]
